# Copyright 2022 Google LLC
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#      http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

on:
  schedule:
    - cron: '0 0 * * *'
  push:
    branches:
      - master
  pull_request:
name: CI
jobs:
  test:
    runs-on: ubuntu-latest
    services:
      emulator:
        image: gcr.io/cloud-spanner-emulator/emulator:1.4.9
        ports:
          - 9010:9010
          - 9020:9020
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-go@v2
        with:
          go-version: '1.14'
      - run: go version
      - name: setup emulator
        run: curl -s 'localhost:9020/v1/projects/myproject/instances' --data '{"instanceId":"myinstance"}'
      - name: run test with emulator
        run: go test -v ./...
        env:
          SPANNER_EMULATOR_HOST: localhost:9010
          SPANNER_DUMP_INTEGRATION_TEST_PROJECT_ID: myproject
          SPANNER_DUMP_INTEGRATION_TEST_INSTANCE_ID: myinstance
